# Generated by Django 3.2.25 on 2024-05-04 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240504_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwotIdeas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Strength', 'Strength'), ('Weakness', 'Weakness'), ('Opportunity', 'Opportunity'), ('Threat', 'Threat')], max_length=20)),
                ('content', models.CharField(max_length=300)),
                ('swot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.swot')),
            ],
        ),
    ]
