# Generated by Django 3.2.13 on 2025-02-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_swotideas'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourPAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(verbose_name='製品')),
                ('price', models.TextField(verbose_name='価格')),
                ('place', models.TextField(verbose_name='流通')),
                ('promotion', models.TextField(verbose_name='販促')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
        ),
    ]
