# Generated by Django 3.2.13 on 2025-02-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_fourpanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourpanalysis',
            name='memo',
            field=models.TextField(blank=True, verbose_name='プロジェクトメモ'),
        ),
        migrations.AddField(
            model_name='fourpanalysis',
            name='overview',
            field=models.TextField(blank=True, verbose_name='概要'),
        ),
    ]
