# Generated by Django 3.2.13 on 2025-02-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_crossswot_crossswotitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossswotitem',
            name='quadrant',
            field=models.CharField(choices=[('SO', '強み×機会'), ('WO', '弱み×機会'), ('ST', '強み×脅威'), ('WT', '弱み×脅威')], max_length=2),
        ),
    ]
