# Generated by Django 4.0.5 on 2025-02-24 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='swotanalysis',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='swot_analysis', to='app.project'),
            preserve_default=False,
        ),
    ]
