
services:
  backend:
    build:
      context: .
      dockerfile: containers/Dockerfile  # Django 用の Dockerfile
    environment:
      - PYTHONPATH=/app
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # React 用の Dockerfile
    volumes:
      - ./frontend:/app
    command: npm run dev
    ports:
      - "5173:5173"
    