# Generated by Django 3.2.25 on 2024-04-28 18:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
        name='YourModel',
        fields=[
            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('field1', models.CharField(max_length=100)),
            ('field2', models.IntegerField()),
            # 必要に応じて他のフィールドを追加します
        ],
    ),
    ]
